apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orders
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders
    spec:
      containers:
        - image: europe-west12-docker.pkg.dev/nestjs-microservices-453105/image-registry/orders
          name: orders
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVERS
              value: "nats://nats"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: orders-secrets
                  key: DATABASE_URL
          resources: {}
status: {}
