version: "3"

services:
  nats-server:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: europe-west12-docker.pkg.dev/nestjs-microservices-453105/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  auth:
    build:
      context: ./auth
      dockerfile: dockerfile.prod
    image: europe-west12-docker.pkg.dev/nestjs-microservices-453105/image-registry/auth
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  products:
    build:
      context: ./products
      dockerfile: dockerfile.prod
    image: europe-west12-docker.pkg.dev/nestjs-microservices-453105/image-registry/products
    environment:
      - PORT=3000
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222

  orders:
    build:
      context: ./orders
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: europe-west12-docker.pkg.dev/nestjs-microservices-453105/image-registry/orders
    environment:
      - PORT=3000
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222

  # orders-db:
  #   image: postgres:16.2
  #   container_name: orders_database
  #   restart: always
  #   volumes:
  #     - ./orders/postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=123456
  #     - POSTGRES_DB=orders

  payments:
    build:
      context: ./payments
      dockerfile: dockerfile.prod
    image: europe-west12-docker.pkg.dev/nestjs-microservices-453105/image-registry/payments
    ports:
      - ${PAYMENTS_PORT}:${PAYMENTS_PORT}
    environment:
      - PORT=${PAYMENTS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_KEY=${STRIPE_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
