apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments
    spec:
      containers:
        - image: europe-west12-docker.pkg.dev/nestjs-microservices-453105/image-registry/payments
          name: payments
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVERS
              value: "nats://nats"
            - name: STRIPE_SUCCESS_URL
              value: "http://localhost:3003/payments/success"
            - name: STRIPE_CANCEL_URL
              value: "http://localhost:3003/payments/cancel"
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: stripe_key
            - name: STRIPE_ENDPOINT_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: stripe_endpoint_secret
          resources: {}
status: {}
