apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client-gateway
  name: client-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client-gateway
    spec:
      containers:
        - image: europe-west12-docker.pkg.dev/nestjs-microservices-453105/image-registry/client-gateway
          name: client-gateway
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVERS
              value: "nats://nats"
          resources: {}
status: {}
